version: '3'

services:
  web:
    build: .
    ports:
      - "8001:8001"  # ローカルの8001ポートをコンテナの8001ポートにマッピング
    volumes:
      - .:/app
      - ./static:/app/static
      - ./logs:/app/logs
    environment:
      - DEBUG=1  # 環境変数設定
